### ISSUE TITLE
Setup raptor-2020 branch in production

### ISSUE THREAD

**Issue by gmierz** [mozilla/perf-youtube-playback#19]
This issue is for setting up an access point in `yttest.prod.mozaws.net/` for the 2020 raptor youtube-playback test.

@bqbn to set this up on the production machine you can follow these steps (I'm not sure of the whole process you may take - let me know if any of this is unclear for you or if you have questions):

1. Clone the repository into the `2020` folder and checkout the raptor-2020 branch with:
 ```git clone --branch raptor-2020 https://github.com/mozilla/perf-youtube-playback 2020```
2. Go to `https://ytlr-cert.appspot.com/2020/main.html` and click `Download-Media-files`. Put this data in the `2020/test-materials/media` folder. (Assuming the data doesn't already come in a `test-materials/media` folder when downloaded).

That should be everything needed. We expect this to be available at `yttest.prod.mozaws.net/2020/main.html`

**Comment by whimboo** [comment]
@gmierz was one of these steps already done?

**Comment by gmierz** [comment]
@whimboo I spoke with whezou about this and we will need to modify the deploy.sh script to change it to the new branch-based year split. After that, we'll be good to go (I'll have this done once I get back from PTO).

**Comment by gmierz** [comment]
It's running here now: https://yttest.prod.mozaws.net/2020/main.html
