### ISSUE TITLE
Update raptor branch for upstream changes on 2020 branch

### ISSUE THREAD

**Issue by whimboo** [mozilla/perf-youtube-playback#6]
There have been a good chunk of updates pushed to the master and 2020 branch of the upstream repository on October 1st:

https://github.com/youtube/js_mse_eme/commits/2020

We should evaluate when those should be merged in, and to be used by default in Raptor tests. Some of them sound kinda interesting and helpful. Also some of our custom patches won't be necessary anytime longer:

https://github.com/youtube/js_mse_eme/commit/bf585033e29d955b657fbce243ab708b315bb526 - Add widevine playback performance test
https://github.com/youtube/js_mse_eme/commit/bb3ad9cef1837444cd3bc33edb17ab912ed0cf61 - Add big buck bunny streams for AV1 30fps and 60fps 
https://github.com/youtube/js_mse_eme/commit/c4dabd350209083073092d4205edf4bd13521b1d -  Check for codec and license support before running each EME test 
https://github.com/youtube/js_mse_eme/commit/38dbaeb557b6c56bc0167b51f7cc6e52178102c7 -  Fast fail MSE conformance/codec tests if no codec support 
https://github.com/youtube/js_mse_eme/commit/ee03a268c72c7cd576462b69b2694f2354d75424 -  Breakdown the PlaybackPerf test suite into smaller pieces 
https://github.com/youtube/js_mse_eme/commit/4facc9199f0eb8bf5b4f85b66ccb6ac6df6f4c31 -  Merge "Add 0.75x Playback Performance Test" 
https://github.com/youtube/js_mse_eme/commit/18695e50f15a8eafa61adc592a4445655a0e5b8b -  Add 1.75x Playback Performance Test 
and maybe some more...

Note that a lot of new tests have been added, which means a longer duration of the tests, and also more output to be handled by raptor and perftest.

@davehunt, @bebef1987, @ionutgoldan could you are all trying to plan the upgrade of our test suite? Thanks

**Comment by davehunt** [comment]
Thanks for raising this @whimboo do you know if/when the 2020 branch is considered stable? @bebef1987 do you think this is something @marianrai could pick up some time this quarter?

**Comment by whimboo** [comment]
I would suggest that you talk to the maintainers of this repository. Given that 2020 comes closer I would suggest that we shall switch sooner than later. The new features look promising, but might also need some adjustments for CI jobs on our side.

**Comment by whimboo** [comment]
It's 2020 now. @davehunt, we should make sure to switch to that new branch. Not sure who will do that. I assume @marianrai?

**Comment by davehunt** [comment]
Yes, @marianrai is actively working on this.

**Comment by gmierz** [comment]
See the raptor-2020 branch for this updated code.
